### ISSUE TITLE
WIN32/MINGW: simple_uart_get_handle, HANDLE unknown

### ISSUE THREAD

**Issue by andkae** [AndreRenaud/simple_uart#11]
Hi André,

when i try to compile to _simple_uart_ for windows i recieve the error:

```bash
simple_uart.h:53:1: error: unknown type name 'HANDLE'
   53 | HANDLE simple_uart_get_handle(struct simple_uart *uart);
      | ^~~~~~
```

Do you know which include is missing to get the data type ```HANDLE```

Thnanks for your support!

BR,
Andreas

**Comment by AndreRenaud** [comment]
Ah yes. That file probably needs the following at the top (just where we the `stdbool` line is).
```c
#ifdef WIN32
#include <windows.h>
#endif
```

**Comment by akaeba** [comment]
I can test and prepare a PR.

**Comment by akaeba** [comment]
added in #14

**Comment by andkae** [comment]
Thanks for merging
