### ISSUE TITLE
Recieve Compile Warning in MSYS2

### ISSUE THREAD

**Issue by andkae** [AndreRenaud/simple_uart#29]
Hello Andre

in this Line:

https://github.com/AndreRenaud/simple_uart/blob/62743ec9b1e288ff6e9f85ee4be98fe62531f618/simple_uart.c#L172C7-L172C30

i recieve a compile warning in MSYS2:

```
./inc/simple_uart/simple_uart.c:172:24: warning: conversion to 'DWORD' {aka 'long unsigned int'} from 'int' may change the sign of the result [-Wsign-conversion]
  172 |     options.BaudRate = speed;
      |                        ^~~~~
```

I can prepare a PR to fix.

**Comment by akaeba** [comment]
Thanks for merge.
