### ISSUE TITLE
QA: simple_uart_term.c only for linux

### ISSUE THREAD

**Issue by andkae** [AndreRenaud/simple_uart#6]
Hi Andre, your cross platform uart driver is a real great thing. Thanks for contribution! The _simple_uart_term.c_ is only intended to use with linux?

BR,
Andreas

**Comment by AndreRenaud** [comment]
Hey Andreas,
It should work on macos & Linux, but it uses termios, so it probably won't work on Windows (maybe with WSL or something). I don't do any real development on Windows machines, so not 100% sure.

Andre

**Comment by andkae** [comment]
Okay. Thanks for answering.
