### ISSUE TITLE
simple_uart_flush in header (.h) but not in implementation (.c)

### ISSUE THREAD

**Issue by andkae** [AndreRenaud/simple_uart#8]
Hi André,

by checking the simple_uart API i found that ```simple_uart_flush``` https://github.com/AndreRenaud/simple_uart/blob/f932d00a6c0629d7ccd35270fd3ef7f81a5f8c3d/simple_uart.h#L66C1-L66C49 is defined in the header but not in the implementation. Is there a special reason to do this in such a way?

Thanks for your answers.

BR,
Andreas

**Comment by AndreRenaud** [comment]
No, I think I just never ported that function across. It should probably be deleted from the header.

**Comment by andkae** [comment]
Would such a functionality make sense to add?

**Comment by AndreRenaud** [comment]
Yes. On non-Win32 platforms, it's probably something like:
```
if (tcdrain(sc->fd) < 0)
    return -errno;
```

On Win32 it might be (unsure on this):
```
if (!FlushFileBuffers(sc->port))
   return -GetLastError();
```

**Comment by andkae** [comment]
Let's give it a try :)

**Comment by andkae** [comment]
Thanks for merge.
